import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import { Container } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <Container p="3" pt="9" pb="9" maxW="lg">
            {children}
          </Container>
        </Provider>
      </body>
    </html>
  );
}
